"""Add workspace_id to AIConversation

Revision ID: 058b508de34c
Revises: b8e986075eb0
Create Date: 2026-07-11 22:43:48.488147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058b508de34c'
down_revision: Union[str, Sequence[str], None] = 'b8e986075eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ai_conversations_workspace_id'), 'ai_conversations', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'ai_conversations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_conversations', type_='foreignkey')
    op.drop_index(op.f('ix_ai_conversations_workspace_id'), table_name='ai_conversations')
    op.drop_column('ai_conversations', 'workspace_id')
    # ### end Alembic commands ###
