"""Add FCM and Notification settings

Revision ID: 0ac6a61235ab
Revises: 837a3de390c2
Create Date: 2026-07-11 15:38:22.364429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ac6a61235ab'
down_revision: Union[str, Sequence[str], None] = '837a3de390c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{"reminders": true, "insights": true, "relationships": true, "system": true}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###
