"""Add memory filters table

Revision ID: 1f2165de766b
Revises: b9f40e10b276
Create Date: 2026-07-25 20:36:55.699105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f2165de766b'
down_revision: Union[str, Sequence[str], None] = 'b9f40e10b276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_filter_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_timeline_sort', sa.String(), nullable=True),
    sa.Column('enabled_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('show_important_first', sa.Boolean(), nullable=True),
    sa.Column('show_frequently_accessed', sa.Boolean(), nullable=True),
    sa.Column('show_recently_discussed', sa.Boolean(), nullable=True),
    sa.Column('show_ai_recommended', sa.Boolean(), nullable=True),
    sa.Column('hide_low_value', sa.Boolean(), nullable=True),
    sa.Column('highlight_active_projects', sa.Boolean(), nullable=True),
    sa.Column('boost_learning_materials', sa.Boolean(), nullable=True),
    sa.Column('boost_work_content', sa.Boolean(), nullable=True),
    sa.Column('boost_personal_content', sa.Boolean(), nullable=True),
    sa.Column('auto_categorization', sa.Boolean(), nullable=True),
    sa.Column('duplicate_detection', sa.Boolean(), nullable=True),
    sa.Column('importance_scoring', sa.Boolean(), nullable=True),
    sa.Column('context_grouping', sa.Boolean(), nullable=True),
    sa.Column('relationship_clustering', sa.Boolean(), nullable=True),
    sa.Column('topic_grouping', sa.Boolean(), nullable=True),
    sa.Column('semantic_grouping', sa.Boolean(), nullable=True),
    sa.Column('timeline_consolidation', sa.Boolean(), nullable=True),
    sa.Column('hide_archived', sa.Boolean(), nullable=True),
    sa.Column('hide_completed_tasks', sa.Boolean(), nullable=True),
    sa.Column('hide_sensitive', sa.Boolean(), nullable=True),
    sa.Column('hide_temporary', sa.Boolean(), nullable=True),
    sa.Column('hide_deleted', sa.Boolean(), nullable=True),
    sa.Column('hide_workspace_memories', sa.Boolean(), nullable=True),
    sa.Column('semantic_search_priority', sa.Boolean(), nullable=True),
    sa.Column('keyword_search_priority', sa.Boolean(), nullable=True),
    sa.Column('hybrid_search', sa.Boolean(), nullable=True),
    sa.Column('relationship_depth', sa.Integer(), nullable=True),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('search_history_enabled', sa.Boolean(), nullable=True),
    sa.Column('search_suggestions', sa.Boolean(), nullable=True),
    sa.Column('ai_context_recent', sa.Boolean(), nullable=True),
    sa.Column('ai_context_pinned', sa.Boolean(), nullable=True),
    sa.Column('ai_context_project', sa.Boolean(), nullable=True),
    sa.Column('ai_context_important', sa.Boolean(), nullable=True),
    sa.Column('ai_context_favourite', sa.Boolean(), nullable=True),
    sa.Column('ai_context_voice', sa.Boolean(), nullable=True),
    sa.Column('ai_context_meeting', sa.Boolean(), nullable=True),
    sa.Column('auto_archive', sa.Boolean(), nullable=True),
    sa.Column('archive_inactivity_days', sa.Integer(), nullable=True),
    sa.Column('never_archive', sa.Boolean(), nullable=True),
    sa.Column('auto_favourite', sa.Boolean(), nullable=True),
    sa.Column('auto_pin', sa.Boolean(), nullable=True),
    sa.Column('keep_recent', sa.Boolean(), nullable=True),
    sa.Column('include_shared', sa.Boolean(), nullable=True),
    sa.Column('exclude_shared', sa.Boolean(), nullable=True),
    sa.Column('workspace_priority', sa.Boolean(), nullable=True),
    sa.Column('personal_priority', sa.Boolean(), nullable=True),
    sa.Column('merged_timeline', sa.Boolean(), nullable=True),
    sa.Column('active_preset', sa.String(), nullable=True),
    sa.Column('saved_presets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_filter_settings')
    # ### end Alembic commands ###
