"""Add NotificationSettings and enhance Notification

Revision ID: 4ab6bcec2488
Revises: 207280ffa6d7
Create Date: 2026-07-28 12:22:48.759971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ab6bcec2488'
down_revision: Union[str, Sequence[str], None] = '207280ffa6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(), nullable=True),
    sa.Column('quiet_hours_end', sa.String(), nullable=True),
    sa.Column('focus_mode_sync', sa.Boolean(), nullable=True),
    sa.Column('weekend_rules_enabled', sa.Boolean(), nullable=True),
    sa.Column('vacation_mode', sa.Boolean(), nullable=True),
    sa.Column('delivery_channels', postgresql.JSONB(astext_type=sa.Text()), server_default='{"push": true, "in_app": true, "daily_digest": false}', nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('smart_suggestions', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('notifications', sa.Column('category', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'category')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
