"""Add GraphSettings model

Revision ID: 65d47000fd31
Revises: a075e424afed
Create Date: 2026-07-25 19:35:17.969503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d47000fd31'
down_revision: Union[str, Sequence[str], None] = 'a075e424afed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('auto_relationship_discovery', sa.Boolean(), nullable=True),
    sa.Column('auto_entity_linking', sa.Boolean(), nullable=True),
    sa.Column('relationship_confidence_threshold', sa.Float(), nullable=True),
    sa.Column('background_updates', sa.Boolean(), nullable=True),
    sa.Column('smart_entity_merging', sa.Boolean(), nullable=True),
    sa.Column('semantic_linking', sa.Boolean(), nullable=True),
    sa.Column('relationship_suggestions', sa.Boolean(), nullable=True),
    sa.Column('auto_merge_similar', sa.Boolean(), nullable=True),
    sa.Column('alias_recognition', sa.Boolean(), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), nullable=True),
    sa.Column('search_type', sa.String(), nullable=True),
    sa.Column('relationship_depth', sa.Integer(), nullable=True),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('include_workspace_graphs', sa.Boolean(), nullable=True),
    sa.Column('hide_sensitive_entities', sa.Boolean(), nullable=True),
    sa.Column('show_relationship_reasons', sa.Boolean(), nullable=True),
    sa.Column('show_confidence_scores', sa.Boolean(), nullable=True),
    sa.Column('show_source_memories', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_settings_user_id'), 'graph_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_settings_user_id'), table_name='graph_settings')
    op.drop_table('graph_settings')
    # ### end Alembic commands ###
