"""Add conversation management and message status

Revision ID: 84444f953a05
Revises: c8cf7d0526bb
Create Date: 2026-07-10 15:13:13.213389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84444f953a05'
down_revision: Union[str, Sequence[str], None] = 'c8cf7d0526bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('ai_conversations', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('ai_conversations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_messages', sa.Column('status', sa.String(), server_default='completed', nullable=False))
    op.add_column('ai_messages', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_messages', 'attachments')
    op.drop_column('ai_messages', 'status')
    op.drop_column('ai_conversations', 'deleted_at')
    op.drop_column('ai_conversations', 'is_archived')
    op.drop_column('ai_conversations', 'is_pinned')
    # ### end Alembic commands ###
