"""Add EncryptionSettings

Revision ID: 89528bb24e9d
Revises: 1b9d83dd6f8c
Create Date: 2026-07-27 20:09:48.200031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89528bb24e9d'
down_revision: Union[str, Sequence[str], None] = '1b9d83dd6f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encryption_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('secure_local_storage', sa.Boolean(), nullable=True),
    sa.Column('encrypted_cache', sa.Boolean(), nullable=True),
    sa.Column('encrypted_temp_files', sa.Boolean(), nullable=True),
    sa.Column('offline_encryption', sa.Boolean(), nullable=True),
    sa.Column('local_db_protection', sa.Boolean(), nullable=True),
    sa.Column('secure_file_storage', sa.Boolean(), nullable=True),
    sa.Column('auto_cache_cleanup', sa.Boolean(), nullable=True),
    sa.Column('encrypted_uploads', sa.Boolean(), nullable=True),
    sa.Column('protected_cloud_storage', sa.Boolean(), nullable=True),
    sa.Column('encrypted_metadata', sa.Boolean(), nullable=True),
    sa.Column('protected_sync', sa.Boolean(), nullable=True),
    sa.Column('secure_api', sa.Boolean(), nullable=True),
    sa.Column('enhanced_protection_categories', postgresql.JSONB(astext_type=sa.Text()), server_default='["financial", "identity", "medical", "passwords", "voice"]', nullable=True),
    sa.Column('default_protection_level', sa.String(), nullable=True),
    sa.Column('sensitive_data_policy', sa.String(), nullable=True),
    sa.Column('export_protection', sa.Boolean(), nullable=True),
    sa.Column('sharing_protection', sa.Boolean(), nullable=True),
    sa.Column('temp_file_lifetime_hours', sa.Integer(), nullable=True),
    sa.Column('encrypted_sharing', sa.Boolean(), nullable=True),
    sa.Column('workspace_encryption', sa.Boolean(), nullable=True),
    sa.Column('protected_shared_links', sa.Boolean(), nullable=True),
    sa.Column('share_expiration_days', sa.Integer(), nullable=True),
    sa.Column('access_restrictions', sa.Boolean(), nullable=True),
    sa.Column('encrypted_backup', sa.Boolean(), nullable=True),
    sa.Column('backup_verification', sa.Boolean(), nullable=True),
    sa.Column('auto_backup_validation', sa.Boolean(), nullable=True),
    sa.Column('backup_integrity_checks', sa.Boolean(), nullable=True),
    sa.Column('restore_verification', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encryption_settings')
    # ### end Alembic commands ###
