"""Add purpose to OTP

Revision ID: 8c1a74a1254e
Revises: bedbaa0794bd
Create Date: 2026-08-17 20:17:45.112109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1a74a1254e'
down_revision: Union[str, Sequence[str], None] = 'bedbaa0794bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_otps', sa.Column('purpose', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_otps', 'purpose')
    # ### end Alembic commands ###
