"""Add theme fields to workspace

Revision ID: 996a14c64b2f
Revises: 058b508de34c
Create Date: 2026-07-11 23:24:06.375963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996a14c64b2f'
down_revision: Union[str, Sequence[str], None] = '058b508de34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('theme_color', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('background_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'background_image_url')
    op.drop_column('workspaces', 'theme_color')
    # ### end Alembic commands ###
