"""Add extended profile fields to users

Revision ID: a075e424afed
Revises: a984a7fac610
Create Date: 2026-07-25 19:00:53.357223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a075e424afed'
down_revision: Union[str, Sequence[str], None] = 'a984a7fac610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(), nullable=True))
    op.add_column('users', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.add_column('users', sa.Column('birthday', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'last_sync')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'social_links')
    op.drop_column('users', 'website')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'country')
    op.drop_column('users', 'language')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
