"""Add Home models for Phase 8

Revision ID: b09e8c3b585b
Revises: 84444f953a05
Create Date: 2026-07-10 20:07:57.564381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b09e8c3b585b'
down_revision: Union[str, Sequence[str], None] = '84444f953a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priorities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_briefs_date'), 'daily_briefs', ['date'], unique=False)
    op.create_index(op.f('ix_daily_briefs_user_id'), 'daily_briefs', ['user_id'], unique=False)
    op.create_table('user_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_insights_user_id'), 'user_insights', ['user_id'], unique=False)
    op.create_table('user_streaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('streak_type', sa.String(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('highest_count', sa.Integer(), nullable=True),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_streaks_user_id'), 'user_streaks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_streaks_user_id'), table_name='user_streaks')
    op.drop_table('user_streaks')
    op.drop_index(op.f('ix_user_insights_user_id'), table_name='user_insights')
    op.drop_table('user_insights')
    op.drop_index(op.f('ix_daily_briefs_user_id'), table_name='daily_briefs')
    op.drop_index(op.f('ix_daily_briefs_date'), table_name='daily_briefs')
    op.drop_table('daily_briefs')
    # ### end Alembic commands ###
