"""Universal Capture Schema

Revision ID: b7c4f466fb41
Revises: bc6a73825797
Create Date: 2026-07-09 18:21:12.210442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7c4f466fb41'
down_revision: Union[str, Sequence[str], None] = 'bc6a73825797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capture_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_value', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capture_entities_capture_id'), 'capture_entities', ['capture_id'], unique=False)
    op.create_table('capture_locations',
    sa.Column('capture_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('nearby_places', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capture_id')
    )
    op.create_table('capture_media',
    sa.Column('capture_id', sa.UUID(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('orientation', sa.String(), nullable=True),
    sa.Column('exif_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capture_id')
    )
    op.create_table('capture_notes',
    sa.Column('capture_id', sa.UUID(), nullable=False),
    sa.Column('rich_text', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('is_pinned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capture_id')
    )
    op.create_table('capture_urls',
    sa.Column('capture_id', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reading_time', sa.Integer(), nullable=True),
    sa.Column('og_image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capture_id')
    )
    op.add_column('captures', sa.Column('status', sa.String(), nullable=True))
    op.add_column('captures', sa.Column('title', sa.String(), nullable=True))
    op.add_column('captures', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('captures', sa.Column('ocr_text', sa.Text(), nullable=True))
    op.add_column('captures', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('captures', sa.Column('storage_path', sa.String(), nullable=True))
    op.add_column('captures', sa.Column('thumbnail_path', sa.String(), nullable=True))
    op.add_column('captures', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('captures', sa.Column('file_size', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_captures_status'), 'captures', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captures_status'), table_name='captures')
    op.drop_column('captures', 'file_size')
    op.drop_column('captures', 'mime_type')
    op.drop_column('captures', 'thumbnail_path')
    op.drop_column('captures', 'storage_path')
    op.drop_column('captures', 'transcript')
    op.drop_column('captures', 'ocr_text')
    op.drop_column('captures', 'summary')
    op.drop_column('captures', 'title')
    op.drop_column('captures', 'status')
    op.drop_table('capture_urls')
    op.drop_table('capture_notes')
    op.drop_table('capture_media')
    op.drop_table('capture_locations')
    op.drop_index(op.f('ix_capture_entities_capture_id'), table_name='capture_entities')
    op.drop_table('capture_entities')
    # ### end Alembic commands ###
