"""Add voice settings table

Revision ID: b9f40e10b276
Revises: 64971c3df49c
Create Date: 2026-07-25 20:28:23.856508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f40e10b276'
down_revision: Union[str, Sequence[str], None] = '64971c3df49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recording_quality', sa.String(), nullable=True),
    sa.Column('auto_gain', sa.Boolean(), nullable=True),
    sa.Column('noise_reduction', sa.Boolean(), nullable=True),
    sa.Column('echo_cancellation', sa.Boolean(), nullable=True),
    sa.Column('silence_detection', sa.Boolean(), nullable=True),
    sa.Column('automatic_stop', sa.Boolean(), nullable=True),
    sa.Column('max_recording_length', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('recognition_language', sa.String(), nullable=True),
    sa.Column('auto_language_detection', sa.Boolean(), nullable=True),
    sa.Column('recognition_accuracy', sa.String(), nullable=True),
    sa.Column('streaming_recognition', sa.Boolean(), nullable=True),
    sa.Column('offline_recognition', sa.Boolean(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('auto_transcribe', sa.Boolean(), nullable=True),
    sa.Column('auto_summary', sa.Boolean(), nullable=True),
    sa.Column('auto_entity_extraction', sa.Boolean(), nullable=True),
    sa.Column('auto_action_detection', sa.Boolean(), nullable=True),
    sa.Column('auto_reminder_detection', sa.Boolean(), nullable=True),
    sa.Column('auto_kg_linking', sa.Boolean(), nullable=True),
    sa.Column('auto_timeline_generation', sa.Boolean(), nullable=True),
    sa.Column('auto_tagging', sa.Boolean(), nullable=True),
    sa.Column('continuous_listening', sa.Boolean(), nullable=True),
    sa.Column('push_to_talk', sa.Boolean(), nullable=True),
    sa.Column('wake_phrase_enabled', sa.Boolean(), nullable=True),
    sa.Column('response_voice', sa.String(), nullable=True),
    sa.Column('response_speed', sa.Float(), nullable=True),
    sa.Column('response_pitch', sa.Float(), nullable=True),
    sa.Column('voice_feedback', sa.Boolean(), nullable=True),
    sa.Column('hands_free_mode', sa.Boolean(), nullable=True),
    sa.Column('playback_speed', sa.Float(), nullable=True),
    sa.Column('pause_between_sentences', sa.Boolean(), nullable=True),
    sa.Column('background_playback', sa.Boolean(), nullable=True),
    sa.Column('auto_resume', sa.Boolean(), nullable=True),
    sa.Column('store_original_audio', sa.Boolean(), nullable=True),
    sa.Column('store_transcript', sa.Boolean(), nullable=True),
    sa.Column('compress_audio', sa.Boolean(), nullable=True),
    sa.Column('auto_delete_original', sa.Boolean(), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('search_audio', sa.Boolean(), nullable=True),
    sa.Column('search_transcript', sa.Boolean(), nullable=True),
    sa.Column('search_speaker', sa.Boolean(), nullable=True),
    sa.Column('search_semantic', sa.Boolean(), nullable=True),
    sa.Column('encrypt_voice_files', sa.Boolean(), nullable=True),
    sa.Column('allow_ai_processing', sa.Boolean(), nullable=True),
    sa.Column('local_processing_preference', sa.Boolean(), nullable=True),
    sa.Column('cloud_processing_preference', sa.Boolean(), nullable=True),
    sa.Column('delete_temp_audio', sa.Boolean(), nullable=True),
    sa.Column('microphone_permission', sa.Boolean(), nullable=True),
    sa.Column('voice_history_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_settings')
    # ### end Alembic commands ###
