"""Add ocr and transcript fields to captures

Revision ID: c8cf7d0526bb
Revises: b7c4f466fb41
Create Date: 2026-07-09 18:50:58.494591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cf7d0526bb'
down_revision: Union[str, Sequence[str], None] = 'b7c4f466fb41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
