"""Add account lifecycle fields to user

Revision ID: e39ce7d4fd4a
Revises: 5636306d02f5
Create Date: 2026-08-01 19:24:56.775894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39ce7d4fd4a'
down_revision: Union[str, Sequence[str], None] = '5636306d02f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    account_status_enum = sa.Enum('ACTIVE', 'PENDING_DELETION', name='accountstatus')
    account_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('account_status', account_status_enum, nullable=False, server_default='ACTIVE'))
    op.add_column('users', sa.Column('deletion_scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletion_scheduled_at')
    op.drop_column('users', 'account_status')
    account_status_enum = sa.Enum('ACTIVE', 'PENDING_DELETION', name='accountstatus')
    account_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
