"""Add ExperienceSettings

Revision ID: e8119a314557
Revises: 89528bb24e9d
Create Date: 2026-07-27 20:34:42.575430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8119a314557'
down_revision: Union[str, Sequence[str], None] = '89528bb24e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('accent_color', sa.String(), nullable=True),
    sa.Column('font_size', sa.String(), nullable=True),
    sa.Column('display_density', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('reading_mode', sa.Boolean(), nullable=True),
    sa.Column('reduce_motion', sa.Boolean(), nullable=True),
    sa.Column('high_contrast', sa.Boolean(), nullable=True),
    sa.Column('color_blind_friendly', sa.Boolean(), nullable=True),
    sa.Column('screen_reader_optimization', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience_settings')
    # ### end Alembic commands ###
