"""Add persona fields

Revision ID: f2ddee8695d2
Revises: 65d47000fd31
Create Date: 2026-07-25 20:02:19.843560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ddee8695d2'
down_revision: Union[str, Sequence[str], None] = '65d47000fd31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_personas', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('role', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('country', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('age_group', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('education_level', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('learning_speed', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('creative_level', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('analytical_level', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('reasoning_depth', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('capture_priority', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('relationship_discovery', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('auto_categorization', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('entity_importance', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('memory_retention', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('timeline_preferences', sa.String(), nullable=True))
    op.add_column('user_personas', sa.Column('graph_expansion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_personas', 'graph_expansion')
    op.drop_column('user_personas', 'timeline_preferences')
    op.drop_column('user_personas', 'memory_retention')
    op.drop_column('user_personas', 'entity_importance')
    op.drop_column('user_personas', 'auto_categorization')
    op.drop_column('user_personas', 'relationship_discovery')
    op.drop_column('user_personas', 'capture_priority')
    op.drop_column('user_personas', 'reasoning_depth')
    op.drop_column('user_personas', 'analytical_level')
    op.drop_column('user_personas', 'creative_level')
    op.drop_column('user_personas', 'learning_speed')
    op.drop_column('user_personas', 'education_level')
    op.drop_column('user_personas', 'age_group')
    op.drop_column('user_personas', 'country')
    op.drop_column('user_personas', 'role')
    op.drop_column('user_personas', 'industry')
    # ### end Alembic commands ###
