/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-tint': 'var(--color-surface-tint)',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'inverse-primary': 'var(--color-inverse-primary)',
        secondary: 'var(--color-secondary)',
        'on-secondary': 'var(--color-on-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        tertiary: 'var(--color-tertiary)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        error: 'var(--color-error)',
        'on-error': 'var(--color-on-error)',
        'error-container': 'var(--color-error-container)',
        'on-error-container': 'var(--color-on-error-container)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        background: 'var(--color-background)',
        'on-background': 'var(--color-on-background)',
        'surface-variant': 'var(--color-surface-variant)',
        white: '#ffffff',
        black: '#000000',
        transparent: 'transparent',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: 'var(--spacing-base, 8px)',
        xs: 'var(--spacing-xs, 4px)',
        sm: 'var(--spacing-sm, 8px)',
        md: 'var(--spacing-md, 16px)',
        lg: 'var(--spacing-lg, 24px)',
        xl: 'var(--spacing-xl, 32px)',
        xxl: 'var(--spacing-xxl, 48px)',
        gutter: 'var(--spacing-gutter, 16px)',
        'margin-mobile': 'var(--spacing-margin-mobile, 20px)',
        'margin-desktop': 'var(--spacing-margin-desktop, 40px)',
      },
      fontFamily: {
        'public-sans': [
          'PublicSans_400Regular',
          'PublicSans_500Medium',
          'PublicSans_600SemiBold',
          'PublicSans_700Bold',
        ],
      },
      fontSize: {
        'display-lg': [
          'var(--fs-display-lg, 44px)',
          { lineHeight: 'var(--lh-display-lg, 52px)', fontWeight: '700', letterSpacing: '-0.02em' },
        ],
        'headline-md': [
          'var(--fs-headline-md, 32px)',
          { lineHeight: 'var(--lh-headline-md, 40px)', fontWeight: '600', letterSpacing: '-0.01em' },
        ],
        'title-sm': ['var(--fs-title-sm, 20px)', { lineHeight: 'var(--lh-title-sm, 28px)', fontWeight: '500' }],
        'body-md': ['var(--fs-body-md, 16px)', { lineHeight: 'var(--lh-body-md, 24px)', fontWeight: '400' }],
        'caption-sm': ['var(--fs-caption-sm, 12px)', { lineHeight: 'var(--lh-caption-sm, 16px)', fontWeight: '400' }],
        'label-xs': [
          'var(--fs-label-xs, 11px)',
          { lineHeight: 'var(--lh-label-xs, 16px)', fontWeight: '500', letterSpacing: '0.05em' },
        ],
      },
    },
  },
  plugins: [],
};
