/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f1',
        'surface-dim': '#e0d9d1',
        'surface-bright': '#fff8f1',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#faf3eb',
        'surface-container': '#f4ede5',
        'surface-container-high': '#eee7df',
        'surface-container-highest': '#e8e1da',
        'on-surface': '#1e1b17',
        'on-surface-variant': '#43474f',
        'inverse-surface': '#33302b',
        'inverse-on-surface': '#f7f0e8',
        outline: '#737780',
        'outline-variant': '#c3c6d1',
        'surface-tint': '#3a5f94',
        primary: '#001e40',
        'on-primary': '#ffffff',
        'primary-container': '#003366',
        'on-primary-container': '#799dd6',
        'inverse-primary': '#a7c8ff',
        secondary: '#006a6a',
        'on-secondary': '#ffffff',
        'secondary-container': '#90efef',
        'on-secondary-container': '#006e6e',
        tertiary: '#002504',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#003d0b',
        'on-tertiary-container': '#5ead5c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#a7c8ff',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#1f477b',
        'secondary-fixed': '#93f2f2',
        'secondary-fixed-dim': '#76d6d5',
        'on-secondary-fixed': '#002020',
        'on-secondary-fixed-variant': '#004f4f',
        'tertiary-fixed': '#a3f69c',
        'tertiary-fixed-dim': '#88d982',
        'on-tertiary-fixed': '#002204',
        'on-tertiary-fixed-variant': '#005312',
        background: '#fff8f1',
        'on-background': '#1e1b17',
        'surface-variant': '#e8e1da',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        gutter: '16px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        'public-sans': [
          'PublicSans_400Regular',
          'PublicSans_500Medium',
          'PublicSans_600SemiBold',
          'PublicSans_700Bold',
        ],
      },
      fontSize: {
        'display-lg': [
          '44px',
          { lineHeight: '52px', fontWeight: '700', letterSpacing: '-0.02em' },
        ],
        'headline-md': [
          '32px',
          { lineHeight: '40px', fontWeight: '600', letterSpacing: '-0.01em' },
        ],
        'title-sm': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'caption-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-xs': [
          '11px',
          { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.05em' },
        ],
      },
    },
  },
  plugins: [],
};
